import os
import sys
import shutil
import subprocess
import urllib.parse
from datetime import datetime

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///e:/Antigravity/Advance-Task-Tracker/database/tasktracker.db")

def run_restore(backup_filepath):
    if not os.path.exists(backup_filepath):
        print(f"Error: Backup file not found at '{backup_filepath}'")
        return False
        
    print(f"[{datetime.now().isoformat()}] Initiating Database Restore process from '{backup_filepath}'...")
    
    if DATABASE_URL.startswith("sqlite:///"):
        # SQLite restore path
        dest_path = DATABASE_URL.replace("sqlite:///", "")
        
        # Create parent dir if missing
        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        
        try:
            # Back up current working database first to avoid accidental loss
            if os.path.exists(dest_path):
                temp_backup = dest_path + ".bak"
                shutil.copy2(dest_path, temp_backup)
                print(f"Info: Saved temporary rollback file at '{temp_backup}'")
                
            shutil.copy2(backup_filepath, dest_path)
            print(f"Success: SQLite database restored successfully from '{backup_filepath}' to '{dest_path}'")
            return True
        except Exception as e:
            print(f"Failed to restore SQLite database: {e}")
            return False
            
    elif DATABASE_URL.startswith("postgresql://") or DATABASE_URL.startswith("postgres://"):
        # PostgreSQL restore
        try:
            parsed = urllib.parse.urlparse(DATABASE_URL)
            db_name = parsed.path.lstrip("/")
            username = parsed.username
            password = parsed.password
            host = parsed.hostname
            port = parsed.port or 5432
            
            # Construct psql command for plain text sql files generated by pg_dump
            cmd = ["psql", "-h", host, "-p", str(port), "-U", username, "-d", db_name, "-f", backup_filepath]
            
            env = os.environ.copy()
            if password:
                env["PGPASSWORD"] = password
                
            print(f"Running psql restore command for database '{db_name}'...")
            result = subprocess.run(cmd, env=env, capture_output=True, text=True)
            
            if result.returncode == 0:
                print(f"Success: PostgreSQL database restored successfully from '{backup_filepath}'")
                return True
            else:
                print(f"psql restore error (code {result.returncode}): {result.stderr}")
                return False
        except Exception as e:
            print(f"Error parsing/running PostgreSQL restore: {e}")
            return False
    else:
        print(f"Unsupported DATABASE_URL scheme in '{DATABASE_URL}'")
        return False

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python restore.py <path_to_backup_file>")
        sys.exit(1)
        
    filepath = sys.argv[1]
    success = run_restore(filepath)
    sys.exit(0 if success else 1)
