"""finance_payroll_workflow

Revision ID: 41e9f484d5e0
Revises: None
Create Date: 2026-06-11 23:22:15.670774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e9f484d5e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('initiator_role', sa.String(length=50), nullable=False),
    sa.Column('approver_role', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_matrix_id'), 'approval_matrix', ['id'], unique=False)
    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('workflow_stage', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_files_file_hash'), 'evidence_files', ['file_hash'], unique=True)
    op.create_index(op.f('ix_evidence_files_id'), 'evidence_files', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_category'), 'workflow_definitions', ['category'], unique=True)
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_table('task_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_stage', sa.String(length=50), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_approvals_id'), 'task_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_task_approvals_task_id'), 'task_approvals', ['task_id'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('assigned_role', sa.String(length=50), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignments_id'), 'task_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_task_assignments_task_id'), 'task_assignments', ['task_id'], unique=False)
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_id'), 'task_comments', ['id'], unique=False)
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.create_table('task_rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('rejected_by', sa.String(length=100), nullable=False),
    sa.Column('rejected_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('rejection_stage', sa.String(length=50), nullable=False),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_rejections_id'), 'task_rejections', ['id'], unique=False)
    op.create_index(op.f('ix_task_rejections_task_id'), 'task_rejections', ['task_id'], unique=False)
    op.create_table('task_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('returned_by', sa.String(length=100), nullable=False),
    sa.Column('returned_to', sa.String(length=100), nullable=False),
    sa.Column('return_reason', sa.Text(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('return_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_returns_id'), 'task_returns', ['id'], unique=False)
    op.create_index(op.f('ix_task_returns_task_id'), 'task_returns', ['task_id'], unique=False)
    op.create_table('user_hierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reports_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reports_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_hierarchy_id'), 'user_hierarchy', ['id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_definition_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.drop_index('ix_files_file_hash', table_name='files')
    op.drop_index('ix_files_id', table_name='files')
    op.drop_table('files')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'evidence_files', ['payroll_evidence_file_id'], ['id'])
    op.drop_constraint(None, 'workflow_activities', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_activities', 'evidence_files', ['evidence_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_activities', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_activities', 'files', ['evidence_file_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'files', ['payroll_evidence_file_id'], ['id'])
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=512), nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('workflow_stage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('approved_by_id', sa.INTEGER(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_id', 'files', ['id'], unique=False)
    op.create_index('ix_files_file_hash', 'files', ['file_hash'], unique=1)
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_user_hierarchy_id'), table_name='user_hierarchy')
    op.drop_table('user_hierarchy')
    op.drop_index(op.f('ix_task_returns_task_id'), table_name='task_returns')
    op.drop_index(op.f('ix_task_returns_id'), table_name='task_returns')
    op.drop_table('task_returns')
    op.drop_index(op.f('ix_task_rejections_task_id'), table_name='task_rejections')
    op.drop_index(op.f('ix_task_rejections_id'), table_name='task_rejections')
    op.drop_table('task_rejections')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_index(op.f('ix_task_comments_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_task_assignments_task_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_id'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index(op.f('ix_task_approvals_task_id'), table_name='task_approvals')
    op.drop_index(op.f('ix_task_approvals_id'), table_name='task_approvals')
    op.drop_table('task_approvals')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_category'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_evidence_files_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_file_hash'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_approval_matrix_id'), table_name='approval_matrix')
    op.drop_table('approval_matrix')
    # ### end Alembic commands ###
